---
services:
  ddnsup:
    image: ghcr.io/jcostom/ddnsup:latest
    container_name: ddnsup
    volumes:
      - /var/docks/ddnsup:/config
    user: 1000:1000
    environment:
      - PROVIDER=dnsomatic
      - DOM_USER=my-username
      - DOM_PASSWD=my-password
      - DOM_MX=NOCHG # optional
      - DOM_BACKUPMX=NOCHG # optional
      - DOM_WILDCARD=NOCHG # optional
      - RECORDS=list,of,hostnames,you,are,updating
      - USETELEGRAM=1
      - CHATID='Your Telegram Chat ID'
      - MYTOKEN='Your Telegram Bot Token'
      - SITENAME='Your Site Identifier'
      - TZ=America/New_York # or whatever makes sense for you
    restart: unless-stopped
    network_mode: bridge
