---
services:
  ddnsup:
    image: ghcr.io/jcostom/ddnsup:latest
    container_name: ddnsup
    volumes:
      - /var/docks/ddnsup:/config
    user: 1000:1000
    environment:
      - PROVIDER=cf
      - CF_APITOKEN=cloudflare-api-token-goes-here
      - CF_ZONEID=cloudflare-zone-id-number
      - CF_TTL=1 # optional
      - CF_PROXIED=false # optional
      - RECORDS=list,of,hostnames,you,are,updating 
      - USE_TELEGRAM=1
      - TELEGRAM_CHATID='Your Telegram Chat ID'
      - TELEGRAM_TOKEN='Your Telegram Bot Token'
      - SITENAME='Your Site Identifier'
      - TZ=America/New_York
      - DEBUG=0
    restart: unless-stopped
    network_mode: bridge
